apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-configmapp
  labels:
    "app.kubernetes.io/name": 'welcome'
    "helm.sh/chart": "welcome-1.0.0"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "example-page"
data:
   nginx.conf: |
    server {
      listen 80;
      location / {
        root /public;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
        default_type application/json;
        return 200 '{"name": "world"}';
      }
    }