apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
{{- if .Values.welcome.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.welcome.deploymentAnnotations | indent 4 }}
{{- end }}
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: html-install
          image: cropio/busybox-wget-https
          command: ["/bin/sh", "-c", "wget -qO public.zip {{ .Values.welcome.assetDownloadURL }} && unzip public.zip -d /public"]
          volumeMounts:
          - name: storage-volume
            mountPath: /public
      containers:
      - name: welcome
        image: nginx:latest
        volumeMounts:
        - name: storage-volume
          mountPath: /public
        - name: config-volume
          mountPath: /etc/nginx/conf.d/
        ports:
        - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: welcome-configmap
        - name: storage-volume
        {{- if .Values.welcome.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.welcome.persistentVolume.existingClaim }}{{ .Values.welcome.persistentVolume.existingClaim }}{{- else }}{{ template "welcome.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.welcome.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.welcome.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
        {{- end -}}