apiVersion: apps/v1
kind: Deployment
metadata:
{{- if .Values.welcome.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.welcome.deploymentAnnotations | indent 4 }}
{{- end }}
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: html-install
          image: busybox
          command:
          - wget
          - "-O"
          - "/temp-public"
          - https://github.com/SeongJuMoon/template-base/releases/download/1.0.0/public.zip
      containers:
      - name: welcome
        image: nginx:latest
        volueMounts:
        - name: storage-volume
          mountPath: /usr/share/nginx/html
        - name: config-volume
          mountPath: /etc/nginx/sites-enabled/default
      volumes:
        - name: config-volume
          configMap:
            name: welcome-configmap
        - name: storage-volume
        {{- if .Values.welcome.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.welcome.persistentVolume.existingClaim }}{{ .Values.welcome.persistentVolume.existingClaim }}{{- else }}{{ template "welcome.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.welcome.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.welcome.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
        {{- end -}}